name: freedesktop_desktop_entry
description: A Dart package for parsing freedesktop (XDG) desktop entries on Linux.
version: 0.6.1
repository: https://github.com/roscale/freedesktop_desktop_entry
issue_tracker: https://github.com/roscale/freedesktop_desktop_entry/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.5
  lints: ^2.1.1
  test: ^1.24.4
